<a href="https://colab.research.google.com/github/YaCpotato/python_tutorial_reading_session/blob/master/NumpyStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpyを完全に理解するノート
## 1. 配列
### 1.1.1 **numpy.array** 一次元配列

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

### 1.1.2 二次元配列

In [0]:
b = np.array([[1,2,3],[4,5,6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 3)

### 1.2 **reshape()** 

reshape(x,y)・・・Numpy配列をy等分して、x行に分割変形する

In [12]:
c = np.array([0,1,2,3,4,5])
c.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

### 1.3 **ravel()**
多次元のNumpy配列を一次元に戻す。戻し方はreshape()の逆

In [14]:
c.ravel()
c

array([0, 1, 2, 3, 4, 5])